version: 1
validation: sovereign
accounts: 
- name: alice
  coins:
  - 20000urise
  - 200000000uvrise
- name: bob
  coins:
  - 10000urise
  - 100000000uvrise
client:
  openapi:
    path: docs/static/openapi.json
faucet:
  name: bob
  coins:
  - 5urise
  - 100000uvrise
validators:
- name: alice
  bonded: 100000000uvrise
- name: validator1
  bonded: 100000000uvrise
- name: validator2
  bonded: 200000000uvrise
- name: validator3
  bonded: 300000000uvrise